terra

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -123,7 +123,13 @@ jobs:
           sudo apachectl configtest
           sudo tail -n 50 /var/log/apache2/error.log
           sudo systemctl status apache2.service
-          sudo systemctl start apache2
+          # Start the Apache server
+          echo "Starting Apache server..."
+          if ! sudo systemctl start apache2 >> /var/log/apache2/startup_script.log 2>&1; then
+              echo "Failed to start Apache server. Check logs for details."
+              capture_logs
+              exit 1  # Exit if Apache fails to start
+          fi
           sudo tail -n 50 /var/log/apache2/error.log
           sudo systemctl enable apache2
           sudo systemctl status apache2.service
